#%RAML 1.0 DataType
#   Copyright [yyyy] [name of copyright owner]
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
type: object
properties:
  wallClock:
    description: Current position of the wall clock at the client in seconds
    type: number
    required: true
  contextClock:
    description: Current position of the reference clock at the client in seconds
    type: number
    required: true
  contextClockRate:
    description: Current relative rate of the reference clock at the client, when not present this defaults to 1 (normal rate)
    type: number
    required: false
    default: 1.0
